version: "3.8"
services:
  postgres:
    image: postgres:latest
    restart: on-failure
    env_file:
      - env/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    depends_on:
      - postgres
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: on-failure
    env_file:
      - env/pgadmin.env
    ports:
      - "5050:80"

  nestjs:
    restart: on-failure
    depends_on:
      - postgres
    build: backend/
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/workspace
    env_file:
      - env/backend.env
    container_name: nestjs

  frontend:
    env_file:
      - env/frontend.env
    container_name: frontend
    restart: on-failure
    build:
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/frontend

volumes:
  db-data:
    driver: local
  nest_volume:
    driver: local
    name: nestjs
    driver_opts:
      device: ./backend
      type: volume
      o: bind

networks:
  transcendence:
    driver: bridge
    name: transcendence_network
